12 new design
Valdior/WASB-Front pull request #18
Opened 2024-04-30 10:06 UTC by KeotiseuF

2024-04-30 12:27 UTC, Valdior requested changes

2024-04-30 12:27 UTC, Valdior commented on src/web3/ternoaConnect.tsx
> +            {!isAccountCertified && <li><NavLink className="dropdown-item" to="/setting">Profile</NavLink></li>}
Il y a un problème dans la logique.
La signature permet juste de valider qu'on est le propiétaire du wallet. 

Pourquoi je n'ai plus accès à ces liens si je suis bien la personne que je prétend être ?

2024-04-30 12:27 UTC, Valdior commented on src/component/register.tsx
>              <Trans i18nKey="register.confidentiality" t={t} components= {
Il faut un checkbox pour valider que la personne a bien lu les documents, on ne peut partir du postulat qu'il l'a bien lu sans une approbation explicite

2024-04-30 12:27 UTC, Valdior commented on src/component/setting.tsx
trop de code identique avec le registrer, faut simplifié :)

2024-04-30 12:27 UTC, Valdior commented on src/component/setting.tsx
pourquoi autant de css  ici ? tu ne sais pas le faire directement en fichier .css ?

2024-05-01 04:19 UTC, KeotiseuF commented on package.json
> +    "@walletconnect/sign-client": "2.0.0-beta.100",
Car j'ai réinstallé tout les packages et en plus supprimer toute les lignes en rapport avec WalletConnect pour tout réinstaller proprement. Par la suite j'avais plus l'erreur de version, ni l'erreur au niveau de l'importation de la variable ERROR. 
![image](https://github.com/Valdior/WASB-Front/assets/101713837/1819d54c-7a6f-4fd7-80f5-651569e38240)

2024-05-01 04:38 UTC, KeotiseuF commented on src/App.scss
> +.padding-button {
Je suis d'accord, j'aurai bien aimé regroupé dans un dossier le fichier css et le fichier tsx concernaient ou sinon créer un dossier spécifique aux css.

App.scss servirait pour mettre les styles utilisés par plusieurs composants, c'est le cas des classes ajoutées ici elles permettent d'ajouter le même desgin à un bouton dans n'importe quel composant.

2024-05-01 04:56 UTC, KeotiseuF commented on src/web3/ternoaConnect.tsx
> +            {!isAccountCertified && <li><NavLink className="dropdown-item" to="/setting">Profile</NavLink></li>}
Ah non la logique n'y fais pas attention, elle est pas encore en place, j'ai laissé comme cela pour que ça reste afficher à l'écran une fois connecter avec le wallet.

2024-05-01 05:04 UTC, KeotiseuF commented on src/component/register.tsx
>              <Trans i18nKey="register.confidentiality" t={t} components= {
![image](https://github.com/Valdior/WASB-Front/assets/101713837/fa6d9903-8b36-4d82-8398-ee17ce1a110b)

On change la phrase en 'Cochez, si vous acceptez d'être contacté...', dit moi si t'es pour.

2024-05-01 05:20 UTC, KeotiseuF commented on src/component/setting.tsx
Au contraire, je préfère séparé le ts du css, on revient à ce que je disais dans le premier commentaire je suis partant pour regrouper les fichiers ensembles par exemple un dossier setting et à l'intérieur un setting.tsx et setting.css. Je suis resté sur la structure de base c'est pour ça

2024-05-01 08:44 UTC, Valdior commented on src/component/register.tsx
>              <Trans i18nKey="register.confidentiality" t={t} components= {
normalement, ca doit être des choses distinctes.
1. pour être contacter
2. pour accepter les conditions 

le 2eme est obligatoire, pas le 1er

2024-05-01 08:46 UTC, Valdior commented on src/component/setting.tsx
Dans ce cas, faut qu'on discute de la manière de procéder et qu'on s'accorde :)

2024-05-09 13:37 UTC, Valdior commented
@KeotiseuF  Ou en es-tu avec cette PR ?

2024-05-09 13:45 UTC, KeotiseuF commented
@Valdior Je dois finir les fonctionnalités du formulaire, normalement à la PR  la partie settings devrait être OK, pour communiqué avec le back

2024-05-14 06:38 UTC, Valdior commented on src/common/Footer.tsx
> +                                <a href='https://discord.gg/hCekNVzGSM' target='_blank'><i className="fa-brands fa-discord fa-2x"></i></a>
mauvais merge, ca a été volontairement retiré

2024-05-14 06:38 UTC, Valdior commented on src/common/Footer.tsx
> +                        <li className="ms-3"><a className="link-light" href='https://discord.gg/hCekNVzGSM' target='_blank'><i className="fa-brands fa-discord"></i></a></li>
idem

2024-05-14 06:38 UTC, Valdior commented on src/common/Footer.tsx
>                  </div>
ttu change completement la div, ok.
Mais pourquoi avoir également retirer ce qui concerne la souscription au newsletter ainsi que le reste du message ?

2024-05-14 06:38 UTC, Valdior commented on src/component/home.tsx
> +                        <a href='https://discord.gg/hCekNVzGSM' target='_blank' className="btn btn-outline-primary bg-opacity-10 text-end" type="button">{t("common.join")} <i className='fa fa-chevron
mauvais merge, ca a été volontairement retiré

2024-05-14 06:38 UTC, Valdior commented on src/hook/Form.tsx
> +        console.log(registration);
retirer les console.log

2024-05-14 06:38 UTC, Valdior commented on src/hook/Form.tsx
> +    console.log(registration);
retirer les console.log

2024-05-14 06:38 UTC, Valdior commented on src/web3/ternoaConnect.tsx
> +                        {!isAccountCertified && <li><NavLink className="dropdown-item" to="/setting">Profile</NavLink></li>}
A placer dans le fichier de traduction

2024-05-14 06:39 UTC, Valdior commented on src/component/setting.tsx
tu n'as pas chercher a simplifié le code entre le settings et le register ?

2024-05-14 06:53 UTC, Valdior commented on package.json
> +    "@walletconnect/sign-client": "2.0.0-beta.100",
Finalement c'était bien nécessaire, il faut le remettre pour que ta PR passe, sinon github plante lors du npm install
![ESLINT install error](image.png)

2024-05-15 16:48 UTC, Valdior commented on src/common/Footer.tsx
> +                                <a href='https://discord.gg/hCekNVzGSM' target='_blank'><i className="fa-brands fa-discord fa-2x"></i></a>
tjr pas fait

2024-05-15 16:48 UTC, Valdior commented on src/component/Home.tsx
> +                        <a href='https://discord.gg/hCekNVzGSM' target='_blank' className="btn btn-outline-primary bg-opacity-10 text-end" type="button">{t("common.join")} <i className='fa fa-chevron
idem

2024-05-15 16:48 UTC, Valdior commented on src/component/register.tsx
Il faut également rename ce fichier non ? register -> Register

2024-05-15 17:37 UTC, Valdior approved these changes

2024-05-15 17:37 UTC, merged