Features/22 eslint
Valdior/WASB-Front pull request #23
Opened 2024-05-06 14:00 UTC by Valdior

2024-05-07 05:15 UTC, KeotiseuF requested changes
Beaucoup de fichier avec de la tabulation en trop.

2024-05-07 05:15 UTC, KeotiseuF commented on .editorconfig
indent_size à 4 je trouve ça fait pas mal, avec 2 beaucoup moins d'espace vide.

2024-05-07 05:15 UTC, KeotiseuF commented on .eslintrc.cjs
Pareil pour l'indent à 4.

2024-05-07 05:15 UTC, KeotiseuF commented on src/App.tsx
Pourquoi rajouter de l'espace en plus ?

2024-05-07 05:15 UTC, KeotiseuF commented on src/component/ConnectionManager.tsx
Pareil des tab en trop

2024-05-07 06:35 UTC, Valdior commented on .editorconfig
j'ai toujours eu un préférence pour 4, ca laisser davantage d'espace et le code est moins compact, plus aéré.

2024-05-07 06:35 UTC, Valdior commented on src/component/ConnectionManager.tsx
c'est l'ESLint qui a ajouter tous ces espaces

2024-05-08 04:41 UTC, KeotiseuF commented on .editorconfig
![image](https://github.com/Valdior/WASB-Front/assets/101713837/4b60fbbf-911a-4d30-bf79-46e3189f62ab)
![image](https://github.com/Valdior/WASB-Front/assets/101713837/8943755e-23a4-47b6-81c9-1626548160a9)

Je te cache pas, je suis pas fan 😅 Regarde toute la place qu'on utilise pour rien, de plus cela nous oblige à passer à la ligne plus rapidement pour avoir un code lisible. Normalement, si tu as des noms de fonction explicites avec des commentaires si besoin, le code ne devrait pas poser de problème.

2024-05-08 08:21 UTC, Valdior commented on .editorconfig
Le screen du bas, c'est bien non ? :o 
C'est celui que j'obtiens après l'eslint

2024-05-08 08:23 UTC, Valdior commented on .editorconfig
Après se sont juste des fichiers de traduction, pas du code. donc je m'en fou un peu

2024-05-09 14:02 UTC, KeotiseuF commented on .editorconfig
Le fichier était juste un exemple ça aurait pu être n'importe quel fichier et de plus là ça à pas bougé car je me suis trompé car il y avait déjà 4 espaces, sorry 😅. 

J'ai confondu avec l'espace car quand je tab, j'ai que 2 espaces, ce que je préfère mais 4 n'est pas dérangent non plus partons pour alors.

2024-05-09 14:27 UTC, merged